function openCustomModal(
  title,
  description,
  buttonText,
  callback = () => {
    console.log('ok');
  }
) {
  // Update modal content
  document.getElementById('modalTitle').innerText = title;
  document.getElementById('modalDescription').innerHTML = description;
  const modalActionButton = document.getElementById('modalActionButton');
  modalActionButton.innerText = buttonText;

  const modal = document.getElementById('exampleModal');
  modal.classList.add('show');
  setTimeout(() => {
    modal.classList.add('in');
  }, 500);

  // Attach callback function to modal action button click
  modalActionButton.addEventListener('click', () => {
    if (typeof callback === 'function') {
      callback(); // Execute the callback function
    }
    closeModal();
  });
}

function closeModal() {
  const modal = document.getElementById('exampleModal');
  modal.classList.remove('in');
  setTimeout(() => {
    modal.classList.remove('show');
  }, 500);
}

function updateTerminalHeader() {
  const statusText = document.getElementById('statusText');
  if (statusText) {
    statusText.textContent = 'Done: Process Success!';
    statusText.classList.add('done');
  }
}


// Fungsi untuk menghasilkan nilai acak dari array
function getRandomValue() {
  const randomOptions = ['3x', '4x', '7x', '10x', '6x'];
  return randomOptions[Math.floor(Math.random() * randomOptions.length)];
}

// Fungsi untuk memformat waktu
function formatTime(time) {
  const date = new Date(time * 1000); // Konversi waktu dari detik ke milidetik
  return date.toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit' });
}

// Fungsi untuk mendapatkan nilai acak antara min dan max (inklusif)
function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

// Fungsi untuk memformat waktu menjadi string (HH:MM)
function formatTime(timestamp) {
    const date = new Date(timestamp * 1000);
    return date.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit', hour12: false });
}

// Fungsi untuk mendapatkan nilai acak untuk "Min Xx"
function getRandomValue() {
    return getRandomInt(3, 10); // Rentang acak untuk "Min Xx"
}

// Fungsi untuk menghitung interval dengan selisih acak antara 5-8 menit
function calculateIntervals() {
    const date = new Date();
    
    // Waktu mulai dihitung dari saat ini + interval acak pertama (5-8 menit)
    let targetTime = new Date(date.getTime() + getRandomInt(5, 8) * 60 * 1000);

    const intervals = [];
    intervals.push(`${formatTime(targetTime.getTime() / 1000)} - Min ${getRandomValue()}x ==> Cairkan`);

    // Generate 4 interval tambahan dengan selisih acak 5-8 menit
    for (let i = 1; i < 5; i++) {
        targetTime.setMinutes(targetTime.getMinutes() + getRandomInt(5, 8)); // Tambahkan waktu secara acak
        intervals.push(`${formatTime(targetTime.getTime() / 1000)} - Min ${getRandomValue()}x ==> Cairkan`);
    }

    return intervals;
}

// Simulasi hasil output
console.log("_connected to spaceman server...\n");
console.log("_creating timestamp...\n");
console.log(calculateIntervals().join("\n"));
console.log("\n_successfull...");



// Ambil elemen <div> dengan id "typed" di dalam <div> dengan id "theTerminal"
const typedElement = document.getElementById('theTerminal').querySelector('#typed');

// Hitung interval
const intervals = calculateIntervals();

// Buat teks HTML dari hasil intervals
let htmlText = '';

// Tambahkan kata-kata sebelum hasil
htmlText += `<p>_connected to spaceman server...</p>`;
htmlText += `<p>_creating timestamp...</p>`;

// Tambahkan hasil interval
intervals.forEach(interval => {
  htmlText += `<p>${interval}</p>`;
});

// Tambahkan kata-kata setelah hasil
htmlText += `<p>_succesfull...</p>`;

// Sisipkan teks HTML ke dalam elemen "typed"
typedElement.innerHTML = htmlText;



$(function () {
  $('#btnSubmit').click(function () {
    var username = $('#txtUsername').val();
    var confirmUsername = $('#txtConfirmUsername').val();
    if (username != confirmUsername) {
      alert('Username tidak Sama.');
      return false;
    }
    return true;
  });
});

$(document).ready(function () {
  var mySound = new buzz.sound('money', { formats: ['wav', 'mp3'] });
  function randomNumber(min, max) {
    return Math.floor(Math.random() * max + min);
  }
  var names = [
    'Dwi21',
    'maya0',
    'Tandoko14',
    'Budiono01',
    'Simbolon14',
    'Raharjo8',
    'Sukarn',
    'Yuda1',
    'gunawan129',
    'Sudiro44',
    'projooo',
    ' Gradus12',
    'bambang00',
    'budiman19',
    'ari11',
    'Slamet',
    'ahsiyap05',
    'joniio',
    'Wibowo2',
    'Purnama1',
    'Nasution9',
    'killer7',
    'hoki7726',
    'winner79',
    'thor77',
    'beruangka',
    'indomie79',
    'seven71',
    'menang89',
    'hands17',
    'doni18',
    'mike11',
    'damar77',
    'come17',
    'alfateha',
    'cinta19',
    'supayam',
    'botak56',
    'ayamjago7',
    'anjay77',
    'wargaarab',
    'selena6',
    'agusfa',
    'bangjago',
    'idpro8',
    'bolehcoba',
    'kalengsusu',
    'ahmad77',
    'LelakiPanas',
    'Anwar71',
    'adis99',
    'cendol1458',
    'anjaybanget',
    'thomas',
    'Waker',
    'Podu',
    'C9Hard',
    'Shiphtur',
    'HOoZy',
    'Chapanya',
    'Dyrus',
    'shopee95',
    'Kurakura',
    'WildTurtl',
    'Malaikat',
    'Hauntzer',
    'Liquid',
    'jessnotitit',
    'Imaqtpie',
    'Spartan',
    'JJackstar',
    'Ekkocat',
    'Liquidmbah',
    'ngking',
    'Looper',
    'TiPMa',
    'Ohhhq',
    'felic',
    'juragan99',
    'icebatu',
    'C9Meteos',
    'jambulkere',
    'cepatkaya',
    'dunamis',
    'Quasmire',
    'scorro',
    'LiquidQuas',
    'GVHauntzer',
    'PengYiliang',
    'Casely',
    'vipp',
    'ibrudu',
    'Zbuum',
    'mamanx',
    'tomat88',
    'lestari115',
    'alucard',
    'Chipotle',
    'TDKkina',
    'DJkartu',
    'Duocek',
    'Mampus15',
    'KonKwon',
    'Nihillmatic',
    'Zaryab',
    'intero',
    'Biofrost',
    'LongCat4',
    'sporty',
    'trotoar',
    'gelaspecah',
    'gelaplah',
    'LiquidXpecial',
    'JayJ',
    'GVCop',
    'iKeNNyu',
    'C9Hai',
    'FunFrock',
    'CLGLourlo',
    'chealse',
    'anjaymara',
    'Aniratak',
    'bieber66',
    'Isuyu',
    'ali5561',
    'rudi984',
    'yudha5498',
    'Jynthe',
    'nasi915',
    'RickyTang',
    'DaBox',
    'pocar51',
    'Hoofspark',
    'DuBuKiD',
    'AdrianMa',
    'GuriAndGunji',
    'stuntopia',
    'RyanChoi',
    'AiShiTeru',
    'naruto',
    'J0kes',
    'C9Bola',
    'C9SoIo',
    'semokbabi',
    'Maryadi99',
    'gunarto',
    'BaamSouma',
    'warsa',
    'gilang',
    'lanang951',
    'septi423',
    'palastri03',
    'rinimantan',
    'babang',
    'Seeiya',
    'ganteng99',
    'hariyah77',
    'maplestreet8',
    'goldenglue',
    'MegaZero',
    'susano',
    'Panchie',
    'fabbbyyy',
    'teraw',
    'iLucent',
    '1k2o1ko12ko12ko2',
    'Bokbokimacat',
    'buntut',
    'LiquidPiglet',
    'playmkngsupport',
    'Gambler',
    'Gaggiano',
    'JJayel',
    'JoopsaKid',
    '1brayle',
    'Azingy',
    'Kebrex',
    'WahzYan',
    'willxo',
    'TailsLoL',
    'darksnipa47',
    'Thyak',
    'JimmyTalon',
    'vane',
    'sooyoung',
    'lalaisland',
    'Lourlo',
    'Sunar',
    'dhan',
    'scarra',
    'hutam',
    'Lock0nStratos',
    'aphromoo',
    'KMadClown',
    'ChaIlengerAhri',
    'maret',
    'Thefatkidfromup',
    'ahqwe5tdoor',
    'Nintenpai',
    'JustJayce',
    'toontown',
    'BasedYoona',
    'GoldStars',
    'ExecutionerKen',
    'nicemoves',
    'InvertedComposer',
    'LiquidIWD',
    'Stan007',
    'woshishabi',
    'JukeKing',
    'xPecake',
    'BlGHUEVOS',
    'Plun',
    'KingCobra',
    'TDKSmoothie',
    'TSMLustboy',
    'C10Meteos',
    'koiq',
    'ohdaughter',
    'PekinWoof',
    'BrandonFtw8',
    'm2sticc',
    'DaiJurJur',
    'DontMashMe',
    'CaseOpened',
    'otte',
    'wutroletoplay',
    'Thurtle',
    'Dodo8',
    'Frostalicious',
    'bobqinXD',
    'MrCarter',
    'Hellkey',
    'Chimonaa1',
    'DaBoxII',
    'GVVicious',
    'Jummychu',
    'PAlNLESS',
    'LiLBunnyFuFuu',
    'Lukeeeeeeeeee',
    'Lattman',
    'Daserer',
    'AlliancePatrick',
    'Lionsexual',
    'St1xxay',
    'Kojolika',
    'CSTCris',
    'KojotheCat',
    'StellaLoussier',
    'Gleebglarbu',
    'Altrum',
    'RiotMeyeA',
    'Rule18',
    'mandatorycloud',
    'Tritan',
    'LiquidDominate',
    'cidadedecack',
    'RoA',
    'BillyBoss',
    'xPepastel',
    'TaketheDraw',
    'ST2g',
    'Migipooop',
    'dKiWiKid',
    'NMEflareszx',
    'Gundamu',
    'imp',
    'DDABONG',
    'Daydreamin',
    'Nightlie',
    'MRHIGHLIGHTREEL',
    'Shweeb',
    'JinMori',
    'Tailsz',
    'Bischu',
    'CRBRakin',
    'Chaox',
    'Grigne',
    'LogicalDan',
    'DAKular',
    'DifferentSword',
    'Geranimoo',
    'InnoX',
    'FishingforUrf',
    'FluffyKittens206',
    'ImJinAh',
    'CloudNguyen',
    'moonway',
    'whoishe',
    'TiensiNoAkuma',
    'Ethil',
    'nothinghere',
    'SuperMetroid',
    'hiimgosu',
    'Mammon',
    'boni',
    'coBBz',
    'waitingforu',
    'LearningToPIay',
    'YiOwO',
    'heavenTime',
    'AnDa',
    'WakaWaka',
    'hashinshin',
    'TDKKez',
    'MariaCreveling',
    'Cypress',
    'YahooDotCom',
    'Phanimal',
    'Aror',
    'linin',
    'BenNguyen',
    'AHHHHHHHHH',
    'Linsanityy',
    'Valkrin',
    'Gate',
    'Allorim',
    'Johnp0t',
    'Superrrman',
    'Laughing',
    'AKAPapaChau',
    'denoshuresK',
    'Anthony',
    'Nightblue3',
    'Aranium',
    'Pallione',
    'BamfDotaPlayer',
    'FakerSama',
    'xiaolan',
    'Sweept',
    'HooManDu',
    'XiaoWeiXiao',
    'HctMike',
    'Revenge',
    'Apauloh',
    'latebloomer',
    'CRBFyre',
    'MongolWarrior',
    'Hiphophammer',
    'CoachLFProTeam',
    'hiimria',
    'Jackoo',
    'Saskio',
    'DadeFakerPawn',
    'GVStvicious',
    'NeonSurge',
    'NMEBodydrop',
    'MatLifeTriHard',
    'faiz',
    'GinormousNoob',
    'IMbz',
    'miqo',
    'VoyboyCARRY',
    'Hakuho',
    'task',
    'themassacre8',
    'Ayr',
    'SeaHorsee',
    'F0rtissimo',
    'GamerXz',
    'Remie',
    'Soghp',
    'Raimazz',
    'Ultimazero',
    'bigfatlp',
    'NMETrashyy',
    'C9LOD',
    'Popuh',
    'kompas',
    'Iamagoodboy',
    'TrollerDog',
    'Descraton',
    'LiquidInoriTV',
    'MiniMe',
    'deniy',
    'Shweebie',
    'KatLissEverdeen',
    'PoppersOP',
    'B1GKr1T',
    'DGB',
    'stephyscute2',
    'TEESEMM',
    'Cyprincess',
    'baohando',
    'urbutts',
    'maplestreeTT',
    'jamee',
    'SawitonReddit',
    'VeryBitter',
    'BenignSentinel',
    'MrJuvel',
    'Denny',
    'antu',
    'DKrupt',
    'LAGEhsher',
    'eLLinOiSe',
    'MochiBalls',
    'Sonnynot6',
    'ixou',
    'Taeyawn',
    'Dezx',
    '7hThintoN',
    'BeautifulKorean',
    'VwSTeesum',
    'TLIWDominate',
    'Vsepr',
    'ktSmurf',
    'Vultix',
    'Soredemo',
    'ROBERTxLEE',
    'AnnieBot',
    'aksn1per',
    'IamFearless',
    'FrostyLights',
    'SoYung',
    'Tuoooor',
    'Polx',
    'Agolite',
    'CloudWater',
    'Delta',
    'LAGOrbwalk',
    'sexycan',
    'SimonHawkes',
    'Rohammers',
    'NMEInnoX',
    'ChineseJester',
    'IAmDoughboy',
    'Cytosine',
    'Vanxer',
    'SDiana2',
    'Araya',
    'TheItalianOne',
    'F1Flow',
    'Kazahana',
    'Malajukii',
    'xiaoweiba',
    'JoshMabrey',
    'shinymew',
    'Event',
    'freelancer18',
    'ZnipetheDog',
    'hiitsviper',
    'HappyBirfdizzay',
    'Abou222',
    'Gir1shot2diamond',
    'KiNGNidhogg',
    'PurpleFloyd',
    'Rathul',
    'Kwaku',
    'BeachedWhaIe',
    '14h',
    'Xpecial',
    'CLGThink',
    'Aiciel',
    'oerh',
    'butttpounder',
    'TalkPIayLove',
    'jordank',
    'TwistyJuker',
    'MeganFoxisGG',
    'NiHaoDyLan',
    'TallerACE',
    'Doomtrobo',
    'Wardrium',
    'TwtchTviLoveSezu',
    'Westrice',
    'iMysterious',
    'BennyHung',
    'EnmaDaiO',
    'xTc4',
    'FallenBandit',
    'RumbIeMidGG',
    'deft1',
    'GochuHunter',
    'XxRobvanxX',
    'DuoChiDianShi',
    'coLBubbadub',
    'LeBulbe',
    'TanHat',
    'Dusty',
    'panciko',
    'Luqma',
    'antoni',
    'LilBuu',
    'Diamond',
    'cesuna',
    'BigolRon',
    'xSojin',
    'fikrij',
    'KingofMemes',
    '111094Jrh',
    'bive',
    'Yammy',
    'FasScriptor',
    'Docxm',
    'GVBunnyFuFuu',
    'Alphabetical',
    'Liquidzig',
    'YouHadNoDream',
    'TINYHUEVOS',
    'Sheepx',
    'GangstaSwerve',
    'LeBulbetier',
    'amandagugu',
    'Rushmore',
    'AnnieCHastur',
    'OverlordForte',
    'Muffintopper66',
    'Kazura',
    'zetsuen',
    'wozhixiangyin',
    'CaptainNuke',
    'alextheman',
    'Seongmin',
    'Working',
    'kyaasenpaix3',
    'gurminder',
    'Dedekp',
    'TGZ',
    'KrucifixKricc',
    'Kevnn',
    'Academiic',
    'ArianaLovato',
    'Elemia',
    'CLGDeftsu',
    'XerbeK',
    'CeIestic',
    'RedEyeAkame',
    'Kerpal',
    'xFSNSaber',
    'MakNooN',
    'Hcore',
    'MrGamer',
    'zeralf',
    'Fenixlol',
    'Indivisible',
    'SHOWMETHEMONEY',
    'Adorations',
    'Niqhtmarex',
    'RambointheJungle',
    'Iucid',
    'iOddOrange',
    'Uncover',
    'DD666666',
    'r0b0cop',
    'VictoricaDebloiz',
    'Gleebglarb',
    'EmperorSteeleye',
    'SillyAdam',
    'whBox',
    'tempname456543',
    'FeedOn',
    'iJesus69',
    'OmegaB',
    'Riftcrawl',
    'Xandertrax',
    'Krymer',
    'TwistedSun',
    'DeTRFShinmori',
    'RiceFox',
    'iKoogar',
    'Mizuji',
    'White',
    'zgerman',
    'Zackyulia',
    'sakurafIowers',
    'xSaury',
    'PiPiPig',
    'Pyrr',
    'TheCptAmerica',
    'NtzNasty',
    'SlowlyDriftnAway',
    'cre4tive',
    'LAGGoldenShiv',
    'FSNDLuffy',
    'NintendudeX',
    'duliniul',
    'Cybody',
    'Odete49',
    'TFBlade',
    'Platoon',
    'CopyCat',
    'Imokaii',
    'TitanDweevil',
    'HeroesOfTheStorm',
    'JRT94',
    'RedBerrrys',
    'Rockblood',
    'YoloOno',
    'BalmungLFT',
    'IreliaCarriesU',
    'LikeAMaws',
    'PaulDano',
    'ErzaScarIet',
    'KiritoKamui',
    'ProofOfPayment',
    'DonPorks',
    'BarronZzZ',
    'Pikaboo',
    'aLeo',
    'MikeytheBully',
    '7Qing',
    'BillyBossXD',
    'DragonRaider',
    'Haughty',
    'KMadClowns',
    'ikORY',
    'Nikkone',
    'WeixiaTianshi',
    'QQ346443922',
    'FoxDog',
    'Tahx',
    'Hawk',
    'Haruka',
    'Scrumm',
    'cackgod',
    'iAmNotSorry',
    'coLROBERTO',
    'jenggot8',
    'MonkeyDufle',
    'M1ssBear',
    'theletter3',
    'Sandrew',
    'RongRe',
    'MrGatsby',
    'xBlueMoon',
    'Merryem',
    'ElkWhisperer',
    'Enticed',
    'Draguner',
    'DeliciousMilkGG',
    'Patoy',
    'Lucl3n3Ch4k0',
    'Smoian',
    'Piaget',
    'Xiaomi',
    'zeflife',
    'IsDatLohpally',
    'HatersWantToBeMe',
    'Blackmill',
    'PrinceChumpJohn',
    'NhatNguyen',
    'Nebulite',
    'IAmTheIRS',
    'TedStickles',
    'LOD',
    'CallMeExtremity',
    'kimjeii',
    'Kappasun',
    'JJJackstar',
    'TSMMeNoHaxor',
    'Zealous',
    'Normalize',
    'Topcatz',
    'KimchimanBegins',
    'DrawingPalette',
    'AnarchyofDinh',
    'hiimxiao',
    'MikeHct',
    'Manco',
    'ChumpJohnsTeemo',
    'Heejae',
    'delirous',
    'Iodus',
    'hanris',
    'Hawez',
    'ThaOGTschussi',
    'TwistedFox',
    'PureCorruption',
    'HotshotGG',
    'Turdelz',
    'ysohardstylez',
    'Brainfre3z',
    'ilyTaylor',
    'Zaineking',
    'QualityADC',
    'LingTong',
    'DyrudeJstormRMX',
    'AnObesePanda',
    'silvermidget',
    'CornStyle',
    'LafalgarTaw',
    'Zeyzal',
    'Meowwww',
    'Pokemorph',
    'JimmyHong',
    'Hoardedsoviet',
    'Nematic',
    'C9Yusui',
    'BlownbyJanna',
    'Sojs',
    'Cerathe',
    'FairieTail',
    'Xeralis',
    'ichibaNNN',
    'SerenityKitty',
    'Contractz',
    'WWvvWvvW,',
    'ReeferChiefer420',
    'WonderfulTea',
    'Gamely',
    'OberonDark',
    'Imunne',
    'Hoeji',
    'xTearz',
    'NicoleKidman',
    'DonDardanoni',
    'Wonderfuls',
    'HentaiKatness69',
    'Ayai',
    'EREnko',
    'Cruzerthebruzer',
    'Connort',
    'Anoledoran',
    'BiggestNoob',
    'suny',
    'TrojanPanda',
    'MasterCoach',
    'Kirmora',
    'wswgou',
    'NMEotterr',
    'DragonxCharl',
    'uJ3lly',
    'moosebreeder',
    'Strompest',
    'Kurumx',
    'Protective',
    'LegacyofHao',
    'DkBnet',
    'koreas',
    'AxelAxis',
    'NiMaTMSiLe',
    'Preachy',
    'WoahItsJoe',
    'Joshuaek',
    'Lemin',
    'Destinedwithin',
    'Afflictive',
    'Nydukon',
    'Herald0fDeath',
    'ChowPingPong',
    'QuanNguyen',
    'interest',
    'Slylittlefox121',
    'VictimOfTalent',
    'chadiansile',
    'iToradorable',
    'BIackWinter',
    'Mazrer',
    'NKSoju',
    'nhocBym',
    'Dreemo',
    'Virus',
    'CowGoesMooooo',
    'Masrer',
    'Michaelcreative',
    'Emanpop',
    'Druiddroid',
    'KevonBurt',
    'Magicians',
    'HiImYolo',
    'LoveSick',
    'kamonika',
    'Chunkyfresh',
    'tongsoojosim',
    'hiimrogue',
    'Zookerz',
    'LiShengShun',
    'DeTFMYumenoti',
    'EddieMasao',
    'AGilletteRazor',
    'andtheknee',
    'Hazedlol',
    'SrsBznsBro',
    'Spreek',
    'Toxil',
    'JustinJoe',
    'Silverblade12345',
    'WalterWhiteOG',
    'SwiftyNyce',
    'Volt',
    'DoctorElo',
    'Connie',
    'DELLZOR',
    'aiopqwe',
    'MidnightBoba',
    'Sikeylol',
    'Warmogger',
    'Melhsa',
    'OmekoMushi',
    'Life',
    'SleepyDinosaur',
    'Leonard',
    'CatVomit',
    'Likang45',
    'PSiloveyou',
    'xtsetse',
    'ClydeBotNA',
    'Cpense',
    'Arakune',
    'shadowshifte',
    'LeeBai',
    'SexualSavant',
    'CornChowder',
    'DeTRFEsteL',
    'Astro',
    'deDeezer',
    'Jayms',
    'v1anddrotate',
    'JGLafter',
    'UhKili',
    'Aceyy',
    'Zik',
    'RiNDiN',
    'Grandederp',
    'KawaiiTheo',
    'Senjogahara',
    'Th3FooL',
    'GusTn',
    'TheTyrant',
    'GoJeonPa',
    'DJJingYun',
    'Egotesticle',
    'IoveLu',
    'OGNEunJungCho',
    'kevybear',
    'ImJas',
    'Agrorenn',
    'Synxia',
    'DouyuTVForgottt',
    'GrimSamurai',
    '6666666666666',
    'RockleeCtrl',
    'Xode',
    'QQ459680082',
    'KittenAnya',
    'Zakard',
    'MARSIRELIA',
    'WallOfText',
    'SireSnoopy',
    'kelppowder',
    'Hxadecimal',
    'onelaugh',
    'MisoMango',
    'PiggyAzalea',
    'MisterDon',
    'VirginEmperor',
    'suzuXIII',
    'P18GEMEINV',
    'Kurumz',
    'kjin',
    'CcLiuShicC',
    'ExileOfTheBlade',
    'Iambbb',
    'Fubguns',
    'Asutarotto',
    'WhatisLove',
    'Niqhtmarea',
    'L0LWal',
    'JannaFKennedy',
    'Steffypoo',
    'KillerHeedonge',
    'AsianSGpotato',
    'whiteclaw',
    'GATOAmyTorin',
    'lovemyRMB',
    'Frostarix',
    'voyyboy',
    'Melo',
    'RiotZALE',
    'ElvishGleeman',
    'givesyouwiings',
    'LoveIy',
    'Packy',
    'Ntzsmgyu',
    'Susice',
    'Dontqqnubz',
    'mikeshiwuer',
    'Chulss',
    'MASTERDING',
    'Scorpionz',
    'KKOBONG',
    'Veeless',
    'NtzMoon',
    'Leesinwiches',
    'RefuseFate',
    'TP101',
    'ozoss0',
    'SeaShell',
    'Baesed',
    'Foolish',
    'jivhust1',
    'KMadKing',
    'CHRlSS',
    'jbraggs',
    'BeefTacos',
    'Xoqe',
    'Naeim',
    'Aerodactyl',
    'Triett',
    '194IQredditor',
    'Pulzar',
    'Windgelu',
    'Suadero',
    'Zulgor',
    'Senks',
    'cAbstracT',
    'SwagersKing',
    'AkameBestGirl',
    'ThePrimaryEdict',
    'arthasqt',
    'Lobstery',
    'MisterOombadu',
    'TheFriendlyDofu',
    'Oryziaslatipes',
    'ugg1',
    'Flandoor',
    'HawkStandard',
    'wimbis',
    'JimmerFredette',
    'VikingKarots',
    'Sorcerawr',
    'Ciscla',
    'Suffix',
    'MrCow',
    'METALCHOCOB0',
    'Dessias',
    'LevelPerfect',
    'midVox',
    'Junha',
    'Hickus',
    'gamepiong',
    'AirscendoSona',
    'HellooKittie',
    'Jesse',
    'Rainaa',
    'ILoveNASoloQ',
    'Colonelk1',
    'DeTRFZerost',
    'Szmao',
    'TacoKat',
    '1tzJustVictor',
    'HomedogPaws',
    'DioDeSol',
    'PeterBrown',
    'FrannyPack',
    'AbsoluteFridges',
    'TheBiddler',
    'ELMdamemitai',
    'Old',
    'Pavle',
    'nathanielbee',
    'MakiIsuzuSento',
    'nweHuang',
    'EvanRL',
    'yorozu',
    'forgivenbow',
    'alexxisss',
    'Cloverblood',
    'Entities',
    'Believe',
    'Chiruno',
    'Xiaobanma',
    'BestJanna',
    'Neko',
    'TheEyeofHorus',
    'IGotSunshine',
    'Shade20',
    'Sprusse',
    'Imacarebear',
    'Kenleebudouchu',
    'LockDownExec',
    'Chubymonkey',
    'HunterHagen',
    'Applum',
    'DaoKho',
    'MrBlackburn',
    'beatmymeat',
    'BestDota2Sona',
    'chubbiercheeks',
    'KillaKast',
    'Betsujin',
    'TheAmberTeahouse',
    'BellaFlica',
    'ManateeWaffles',
    'Babalew',
    'charmanderu',
    'TooSalty',
    'LotusBoyKiller',
    'Bulgogeeeee',
    'Nerzhu1',
    'Lovelyiris',
    'QuantumFizzics',
    'freakingnoodles',
    'Pdop1',
    'Bakudanx',
    'Martel',
    'DoctorDoom',
    'equalix',
    'CARDCAPTORCARD',
    'Dyad',
    'Papasmuff',
    'TheBroskie',
    'Wadenation',
    'Flyinpiggy',
    'Wingsofdeathx',
    'IamOsiris',
    'ArtThief',
    'LotusEdge',
    'fwii',
    'Kios',
    'Shampu',
    'Nickpappa',
    'Yukari',
    'RayXu',
    'fergiana',
    'TwoPants',
    'EnzoIX',
    'Jacka',
    'Plumber',
    'Skadanton',
    'dans',
    'BonQuish',
    'rajab',
    'SmoSmoSmo',
    'MewtMe',
    'Ramzlol',
    'Mruseless',
    'Eitori',
    'S0lipsism',
    'X1337Gm4uLk03rX',
    'lloveOreo',
    'MrChivalry',
    'Oyt',
    'AnVu',
    'RBbabbong',
    'MASTERROSHl',
    'dabestmelon',
    'Potatooooooooooo',
    'KasuganoHaru',
    'C9BalIs',
    'stainzoid',
    'sisakti1',
    'sweetinnocence',
    'Firehazerd',
    'EpicLynx',
    '2011',
    'PandaCoupIe',
    'Moelon',
    'KingKenneth',
    'Skinathonian',
    'FelixCC',
    'snowmine',
    'Acme',
    'jphoki',
    'Fexir',
    'ImbaDreaMeR',
    'ImNovel',
    'ButtercupShawty',
    'touch',
    'penguin',
    'Promitio',
    'DeTRFMoyashi',
    'Hordstyle',
    'Iizard',
    'Jintae',
    'pichumy',
    'Upu',
    'Iemonlimesodas',
    'TwitchTvAuke',
    'Promises',
    'Jintea',
    'OMikasaAckermanO',
    'kontolroku',
    'Kiyoon',
    'LiquidNyjacky',
    'ATColdblood',
    'fitrahl',
    '0Sleepless',
    'Product',
    'InFusXxx',
    'arsya',
    'edho',
    'firdaus',
    'kems',
    'Pcboy',
    'edon',
    'dudut',
    'soum',
    'Luqman',
    'fikrij',
    'Uchid',
    'shaj',
    'alans',
    'jans',
    'joshuae',
    'jengg',
    'broIy',
  ];
  var countriesCode = ['id'];
  function commentsStart() {
    setInterval(
      function () {
        $('#loadingActivity').fadeOut(150, function () {
          $('#onlineActivity').fadeIn().removeClass('hidden');
        });
        if ($('.activityItem').length > 2) {
          $($('.activityItem')[0]).fadeOut(450, function () {
            $(this).remove();
            $(
              '<section class="activityItem"><p><span class="flag-id"><img src="images/flag.webp"></span> <span id="commentUsername">' +
                names[randomNumber(0, names.length - 1)] +
                '***' +
                '</span> 𝐌𝐄𝐍𝐆𝐆𝐔𝐍𝐀𝐊𝐀𝐍' +
                '𝐀𝐏𝐋𝐈𝐊𝐀𝐒𝐈</p></section>'
            )
              .appendTo('#activityBody')
              .hide()
              .fadeIn(450);
            mySound.play();
          });
        } else {
          if ($('.activityItem').length < 3) {
            $(
              '<section class="activityItem"><p><span class="flag-id"><img src="images/flag.webp"></span> <span id="commentUsername">' +
                names[randomNumber(0, names.length - 1)] +
                '***' +
                '</span> 𝐌𝐄𝐍𝐆𝐆𝐔𝐍𝐀𝐊𝐀𝐍' +
                ' 𝐀𝐏𝐋𝐈𝐊𝐀𝐒𝐈</p></section>'
            )
              .appendTo('#activityBody')
              .hide()
              .fadeIn(450);
            mySound.play();
          }
        }
      },
      randomNumber(2500, 100)
    );
  }
  commentsStart();
  setTimeout(function () {
    $('.spinner').fadeOut(function () {
      $('.container').fadeIn().removeClass('hidden');
      // $('body').css('background', 'url(img/1.jpg) repeat fixed');
    });
  }, 100);
  $('#modalTrigger').on('click', function () {
    $('#theTerminal').fadeOut(function () {
      $('#theVerification').fadeIn().removeClass('hidden');
    });
  });

  $('#daftarsitus').validate({
    submitHandler: function (form) {
      $('#daftarsitus').fadeOut(function () {
        $('#situsjudi').fadeIn().removeClass('hidden');
      });
    },
  });
  $('#situsjudi').validate({
    submitHandler: function (form) {
      $('#situsjudi').fadeOut(function () {
        $('#firstForm').fadeIn().removeClass('hidden');
      });
    },
  });

 


  $('#firstForm').validate({
    rules: { InputUsername: { required: true, minlength: 1 } },
    messages: { InputUsername: 'Masukkan username yang terdaftar!' },
    submitHandler: function (form) {
      $('#firstForm').fadeOut(function () {
        $('#secondForm').fadeIn().removeClass('hidden');
      });
    },
  });
  $('#secondForm').validate({
    submitHandler: function (form) {
      $('#secondForm').fadeOut(function () {
        $('#theTerminal').fadeIn().removeClass('hidden');
        $('#typed').typewriter({
          rotatingLetters: 10,
          speed: 20,
          chars: 'ABCD0123!@#$abcd',
          // callback: function () {
          //   openCustomModal(
          //     'CONGRATULATIONS!',
          //     'Your Account Has Been Injected Cheat SLOT SCATTER .<br /><div style="font-size: medium;font-style: italic;margin-top:15px;color: #4c99dc;">(Selamat id and sudah berhasil terinject winrate 89% - 99%, Silakan langsung bermain di situs yang anda daftarkan.)</div>',
          //     'Play Slot',
          //     () => {
          //       window.open(
          //         'https://gatottech.io/pasti-gacor',
          //         'situs1',
          //         'width=800, height=600, status=1,scrollbar=yes'
          //       );
          //     }
          //   );
          //   updateTerminalHeader();
          // },
        });
      });
    },
  });
});


